apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../manifests/

helmCharts:
- name: backend
  repo: https://sieunhantanbao.github.io/sd2411-helm-charts/
  version: "0.1.0"
  releaseName: backend
  namespace: qa
  valuesFile: backend-values.yaml