# Step 1: Run this command to create SSH KeyPair
# ssh-keygen -t sd2411_infrastructure -C "sieunhantanbao@gmail.com" -f ~/.ssh/sd2411_infrastructure
# Step 2: Get the publish key to add to Github repository
# => cat ~/.ssh/argocd_ed25519.pub
# Step 3: Gte the private key to pass to the below 'sshPrivateKey'
# => cat ~/.ssh/argocd_ed25519
---
apiVersion: v1
kind: Secret
metadata:
  name: sd2411_azure_infrastructure
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:sieunhantanbao/sd2411_azure_infrastructure.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACB/REVPQjZQU6tCo8wsy9YzVzpLlPP7I60fa2rS8PHYUwAAAKDf0FvU39Bb
    1AAAAAtzc2gtZWQyNTUxOQAAACB/REVPQjZQU6tCo8wsy9YzVzpLlPP7I60fa2rS8PHYUw
    AAAEC0ffLk79lzsgCC65wPnetv1XP7AjLNXGHYkwbP8Fibyn9ERU9CNlBTq0KjzCzL1jNX
    OkuU8/sjrR9ratLw8dhTAAAAGHNpZXVuaGFudGFuYmFvQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"