apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - secret.yaml

helmCharts:
- name: frontend
  repo: https://sieunhantanbao.github.io/sd2411-helm-charts/
  version: "5.0.0" # Without ingress
  releaseName: frontend
  namespace: prod
  valuesFile: frontend-values.yaml