apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresdb-qa
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sieunhantanbao/sd2411_azure_infrastructure.git
    targetRevision: main
    path: argocd/helm/qa/apps/postgresdb
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true