apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-qa
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sieunhantanbao/sd2411_azure_infrastructure.git
    targetRevision: main
    path: helm-charts/charts/backend/
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sourcePath: manifests/
  helm:
    valueFiles:
    - ./values/backend-values.yaml
    