apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-qa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: acranhnguyens.azurecr.io/backend
    argocd-image-updater.argoproj.io/example.update-strategy: latest
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sieunhantanbao/sd2411_azure_infrastructure.git
    targetRevision: main
    path: argocd/helm/qa/apps/backend
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true