apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-qa
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sieunhantanbao/sd2411_azure_infrastructure.git
    targetRevision: main
    path: argocd/helm/qa/
    helm:
      chart: "frontend"
      releaseName: qa-frontend-release
      repoURL: https://sieunhantanbao.github.io/sd2411-helm-charts/
      valueFiles:
      - ./values/frontend-values.yaml
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sourcePath: manifests/