apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: mongo
  repo: https://sieunhantanbao.github.io/sd2411-helm-charts/
  version: "1.0.0"
  releaseName: mongo
  namespace: qa
  valuesFile: mongo-values.yaml