# Replica count for the frontend deployment
replicaCount: 2

# name of resources such as deployment, container, service
name: frontend

# Image repository and tag for the frontend container
image:
  repository: acranhnguyens.azurecr.io/frontend
  pullPolicy: Always
  tag: "10"
  imagePullSecret: 'my-acr-secret'

# Port for the frontend service
servicePort: 3000