apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: frontend
  repo: https://sieunhantanbao.github.io/sd2411-helm-charts/
  version: "0.1.0"
  releaseName: frontend
  namespace: qa
  valuesFile: frontend-values.yaml