apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - secret.yaml
helmCharts:
- name: frontend
  repo: https://sieunhantanbao.github.io/sd2411-helm-charts/
  version: "3.0.0"
  releaseName: frontend
  namespace: qa
  valuesFile: frontend-values.yaml
images:
- name: acranhnguyens.azurecr.io/frontend
  newTag: "34"
